# Generated by Django 5.2.17 on 2026-09-09 21:31

import django.db.models.deletion
import shared_kernel.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=shared_kernel.ids.new_uuid7, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=255)),
                ('status', models.CharField(default='provisioning', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenants',
            },
        ),
        migrations.CreateModel(
            name='TenantDatabase',
            fields=[
                ('id', models.UUIDField(default=shared_kernel.ids.new_uuid7, editable=False, primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=3306)),
                ('name', models.CharField(max_length=64)),
                ('secret_ref', models.CharField(max_length=128)),
                ('tls_required', models.BooleanField(default=False)),
                ('status', models.CharField(default='allocating', max_length=32)),
                ('schema_version', models.CharField(default='', max_length=64)),
                ('last_health_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='database', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'tenant_databases',
            },
        ),
        migrations.CreateModel(
            name='TenantProvisioningJob',
            fields=[
                ('id', models.UUIDField(default=shared_kernel.ids.new_uuid7, editable=False, primary_key=True, serialize=False)),
                ('step', models.CharField(default='created', max_length=32)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisioning_jobs', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'tenant_provisioning_jobs',
            },
        ),
        migrations.CreateModel(
            name='TenantMigrationJob',
            fields=[
                ('id', models.UUIDField(default=shared_kernel.ids.new_uuid7, editable=False, primary_key=True, serialize=False)),
                ('source_version', models.CharField(blank=True, default='', max_length=64)),
                ('target_version', models.CharField(max_length=64)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('canary', models.BooleanField(default=False)),
                ('last_error', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migration_jobs', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'tenant_migration_jobs',
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'locked', 'running'])), fields=('tenant',), name='tenancy_one_active_migration')],
            },
        ),
    ]
