# Generated by Django 5.2.17 on 2026-09-09 22:01

import django.db.models.deletion
import shared_kernel.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSettings',
            fields=[
                ('id', models.UUIDField(default=shared_kernel.ids.new_uuid7, editable=False, primary_key=True, serialize=False)),
                ('stripe_webhook_secret_ref', models.CharField(default='STRIPE_WEBHOOK_SECRET', max_length=128)),
                ('braintree_webhook_secret_ref', models.CharField(default='BRAINTREE_WEBHOOK_SECRET', max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'billing_settings',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=shared_kernel.ids.new_uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(default='active', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'billing_plans',
            },
        ),
        migrations.CreateModel(
            name='BillingIdempotencyKey',
            fields=[
                ('id', models.UUIDField(default=shared_kernel.ids.new_uuid7, editable=False, primary_key=True, serialize=False)),
                ('actor_id', models.UUIDField()),
                ('key', models.CharField(max_length=128)),
                ('kind', models.CharField(max_length=32)),
                ('resource_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'billing_idempotency_keys',
                'unique_together': {('actor_id', 'key')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceIndex',
            fields=[
                ('invoice_id', models.UUIDField(primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField()),
                ('customer_id', models.UUIDField()),
                ('status', models.CharField(max_length=32)),
                ('total_minor', models.BigIntegerField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'billing_invoice_index',
                'indexes': [models.Index(fields=['tenant_id', 'customer_id'], name='idx_inv_idx_tenant')],
            },
        ),
        migrations.CreateModel(
            name='PaymentProcessorEvent',
            fields=[
                ('id', models.UUIDField(default=shared_kernel.ids.new_uuid7, editable=False, primary_key=True, serialize=False)),
                ('processor', models.CharField(max_length=32)),
                ('event_id', models.CharField(max_length=128)),
                ('invoice_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(default='received', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'billing_processor_events',
                'unique_together': {('processor', 'event_id')},
            },
        ),
        migrations.CreateModel(
            name='PlanVersion',
            fields=[
                ('id', models.UUIDField(default=shared_kernel.ids.new_uuid7, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('price_minor', models.BigIntegerField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('included_minutes', models.PositiveIntegerField()),
                ('allow_topups', models.BooleanField(default=False)),
                ('topup_minutes', models.PositiveIntegerField(default=0)),
                ('topup_price_minor', models.BigIntegerField(default=0)),
                ('overage_enabled', models.BooleanField(default=False)),
                ('overage_price_per_minute_minor', models.BigIntegerField(default=0)),
                ('grace_seconds', models.PositiveIntegerField(default=0)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='billing.plan')),
            ],
            options={
                'db_table': 'billing_plan_versions',
                'unique_together': {('plan', 'version')},
            },
        ),
    ]
