# Generated by Django 5.2.17 on 2026-09-09 20:56

import django.db.models.deletion
import shared_kernel.ids
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=shared_kernel.ids.new_uuid7, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'identity_users',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=shared_kernel.ids.new_uuid7, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('principal_type', models.CharField(max_length=16)),
                ('role', models.CharField(max_length=64)),
                ('tenant_id', models.UUIDField(blank=True, null=True)),
                ('customer_id', models.UUIDField(blank=True, null=True)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(default='invited', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'identity_invitations',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=shared_kernel.ids.new_uuid7, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'identity_user_sessions',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=shared_kernel.ids.new_uuid7, editable=False, primary_key=True, serialize=False)),
                ('principal_type', models.CharField(max_length=16)),
                ('role', models.CharField(max_length=64)),
                ('tenant_id', models.UUIDField(blank=True, null=True)),
                ('customer_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'identity_memberships',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('principal_type', 'platform'), ('tenant_id__isnull', True), ('customer_id__isnull', True)), models.Q(('principal_type', 'agency'), ('tenant_id__isnull', False), ('customer_id__isnull', True)), models.Q(('principal_type', 'customer'), ('tenant_id__isnull', False), ('customer_id__isnull', False)), _connector='OR'), name='identity_membership_scope')],
            },
        ),
    ]
