# Generated by Django 5.2.17 on 2026-09-09 22:09

import django.db.models.deletion
import shared_kernel.ids
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=shared_kernel.ids.new_uuid7, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField()),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(max_length=32)),
                ('method_label', models.CharField(default='bank', max_length=64)),
                ('transaction_ref', models.CharField(blank=True, default='', max_length=64)),
                ('receipt_number', models.CharField(blank=True, default='', max_length=64)),
                ('requested_by_id', models.UUIDField()),
                ('decided_by_id', models.UUIDField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'commission_payouts',
            },
        ),
        migrations.CreateModel(
            name='WalletLock',
            fields=[
                ('tenant_id', models.UUIDField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'commission_wallet_locks',
            },
        ),
        migrations.CreateModel(
            name='CommissionIdempotencyKey',
            fields=[
                ('id', models.UUIDField(default=shared_kernel.ids.new_uuid7, editable=False, primary_key=True, serialize=False)),
                ('actor_id', models.UUIDField()),
                ('key', models.CharField(max_length=128)),
                ('resource_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'commission_idempotency_keys',
                'unique_together': {('actor_id', 'key')},
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=shared_kernel.ids.new_uuid7, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField()),
                ('customer_id', models.UUIDField(blank=True, null=True)),
                ('kind', models.CharField(max_length=32)),
                ('amount_minor', models.BigIntegerField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_id', models.UUIDField(blank=True, null=True)),
                ('invoice_id', models.UUIDField(blank=True, null=True)),
                ('commission_id', models.UUIDField(blank=True, null=True)),
                ('payout_id', models.UUIDField(blank=True, null=True)),
                ('eligible_base_minor', models.BigIntegerField(blank=True, null=True)),
                ('rate_bps_snapshot', models.PositiveIntegerField(blank=True, null=True)),
                ('earned_at', models.DateTimeField(blank=True, null=True)),
                ('available_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'commission_ledger_entries',
                'indexes': [models.Index(fields=['tenant_id', 'created_at'], name='idx_ledger_tenant'), models.Index(fields=['payment_id'], name='idx_ledger_payment')],
                'constraints': [models.UniqueConstraint(fields=('kind', 'payment_id'), name='uq_ledger_kind_payment'), models.UniqueConstraint(fields=('kind', 'commission_id'), name='uq_ledger_kind_commission')],
            },
        ),
        migrations.CreateModel(
            name='PayoutProof',
            fields=[
                ('payout', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='proof', serialize=False, to='commission.payout')),
                ('object_ref', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=128)),
                ('checksum', models.CharField(max_length=128)),
                ('uploaded_by_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'commission_payout_proofs',
            },
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['tenant_id', 'status'], name='idx_payout_tenant'),
        ),
    ]
